# -*- coding: utf-8 -*-
"""P-test&T-test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eld2KZnDxUJ9MytG2JbYEd-1_cQsIvdN
"""

import scipy.stats as stats
import numpy as np

popu_mean = 45
s_mean = 75
s_std = 25
s_size = 25

t_stat = (s_mean - popu_mean)/(s_std / np.sqrt(s_size))
df = s_size - 1
alpha = 0.05
cr_t = stats.t.ppf(1 - alpha, df)

cr_t

p_v = 1 - stats.t.cdf(t_stat, df)

p_v

print("T-Statistic:", t_stat)
print("Critical t-value:", cr_t)
print("P-Value:", p_v)

print('With T-value :')
if t_stat > cr_t:
  print('Significant difference. Camp had effect.')
else:
  print('No significant difference. Camp had no effect.')

print('With P-value :')
if p_v < alpha:
  print('Significant difference. Camp had effect.')
else:
  print('No significant difference. Camp had no effect.')

from scipy import stats
import numpy as np

A = np.array([4,4,7,16,20,11,13,9,11,15])
B = np.array([15, 16, 14, 14, 22, 22, 23, 18, 18, 19])

t_val, p_val = stats.ttest_rel(A, B)
alpha = 0.05
df = len(A) - 1

c_t = stats.t.ppf(1 - alpha/2, df)
print('T-value:', t_val)
print('P-value:', p_val)
print('Critical t-value:', c_t)

print('T-test:')
if np.abs(t_val) > c_t:
  print('Significant difference found.')
else:
  print('No significant difference.')

print('P-test:')
if p_val < alpha:
  print('Reject H0')
else:
  print('Fail to reject H0')